language: java
jdk:
  - oraclejdk8
sudo: true
before_install:
  - echo 'America/Los_Angeles' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - chmod 755 ./shared/dev-tasks/*.sh
  - chmod 755 ./gradlew
install:
  - ./shared/dev-tasks/install-dependencies.sh
script:
  - ./shared/dev-tasks/run-tests.sh

#whitelist
branches:
  only:
    - master
    - dev
